version: '3.8'

services:
  node-api:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: fableapiuser
      POSTGRES_PASSWORD: fableapipassword
      POSTGRES_DB: fableapidb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-api

volumes:
  postgres-data:
    driver: local