version: '3.8'

services:
  node-api:
    build: .
    ports:
      - "3300:3300"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  nginx:
    image: nginx:latest
    ports:
      - "83:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-api

volumes:
  postgres-data:
    driver: local